### ISSUE TITLE
Install-WSMan Not Working on Big Sur 11.2.2 on a 2020 M1 MacBook Pro

### ISSUE THREAD

**Issue by KeithSieman** [jborean93/omi#37] opened 2021-09-27 01:18 UTC
##### SUMMARY
Install-WSMan returns:

```
PS /private/tmp> Install-WSMan -Verbose 
VERBOSE: Attempting to get OpenSSL info with brew --prefix openssl
STDOUT: /opt/homebrew/opt/openssl@3

STDERR: 
RC: 0
VERBOSE: Attempting to get OpenSSL info port contents openssl
VERBOSE: Host Info:

Install-WSMan: Failed to select the necessary library, the host isn't macOS, Linux based on GLIBC or musl, or OpenSSL isn't installed
```

##### LIBMI VERSION

```
The link in the comment returns a 404 Error.....
```

##### OS / ENVIRONMENT

```
PS /private/tmp> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Darwin 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS /private/tmp> 
```

```
PS /private/tmp> openssl version
LibreSSL 2.8.3
```

**Comment by wtfiwtz** [comment] 2021-09-30 02:01
There are many existing issues, even on Intel laptops - https://github.com/PowerShell/PowerShell/issues/11216

**Comment by jborean93** [comment] 2021-09-30 23:11
This is a duplicate of https://github.com/jborean93/omi/issues/26. The `openssl` at `/opt/homebrew` is the ARM library which is not usable by x64 pwsh/omi (you cannot combine them both). To solve this you need to

* Install the x64 Homebrew which resides in `/usr/local`
* Use that to install an x64 version of OpenSSL
* Ensure `brew` for x64 is first in the `PATH` when you are running `pwsh
* Run `Install-WSMan`

This is not ideal and I'm hoping to make this a bit better which is why I opened https://github.com/jborean93/omi/issues/26.

**Closed** 2021-09-30 23:33 UTC
